### DISCUSSION TITLE
Custom styling <InfoWindow>

### DISCUSSION THREAD

**Discussion by rol4nd909** [visgl/react-google-maps#235] [Q&A]
Hi,

I hope someone can tell me how I can style or create a custom `InfoWindow`?

Thanks in advance.
<img width="620" alt="Screenshot 2024-02-23 at 11 23 27" src="https://github.com/visgl/react-google-maps/assets/1931880/0848c4aa-0937-46af-8a23-1a6cf460a8be">

**Comment by usefulthink** [comment]
You absolutely can. A simple approach is to use the `<AdvancedMarker>` component for this, since it accepts any HTML as content. In this case the bottom/center point of the provided html-element will be placed exactly at the specified coordinates. More advanced implementations might use the `google.maps.OverlayView` and implement something completely custom.

**Reply by rol4nd909** [reply]
Thanks, I will try this out.

**Comment by rol4nd909** [comment]
Not sure what I'm doing wrong, but the pins go on top of the info-container?

this is the code

```tsx
    <AdvancedMarker
      onClick={() => onToggle(!isOpen)}
      position={{
        lat: Number(dealer.location_lat),
        lng: Number(dealer.location_long),
      }}
      title={dealer.name}
      collisionBehavior={google.maps.CollisionBehavior.OPTIONAL_AND_HIDES_LOWER_PRIORITY}
    >
      <div className={classes.markerContainer}>
        {isOpen && (
          <div className={classes.mapInfoWindow}>
            <strong>{dealer.name}</strong>
            <address>
              {dealer.street_name} {dealer.house_number}
              <br />
              {dealer.zipcode}, {dealer.city}
            </address>

            <button
              className={classes.mapsSelectDealerButton}
              type="button"
              onClick={() => setValue(name, dealer.id.toString())}
            >
              {String(dealer.id) === value ? translations.selected : translations.select}
            </button>
          </div>
        )}
        <div className={classes.mapMarker} />
      </div>
    </AdvancedMarker>
```

```scss
.DealerChooser {
  &-markerContainer {
    display: grid;
    font-size: 1rem;
    gap: 1rem;
    justify-items: center;
  }

  &-mapInfoWindow {
    display: grid;
    border: 1px solid #ddd;
    background-color: #fff;
    gap: 1rem;
    inline-size: 16.5rem;
    padding-block: 1.25rem 1.5rem;
    padding-inline: 1.5rem;

    > * {
      margin: 0;
    }
  }

  &-mapMarker {
    --marker-color: #de0039;
    --marker-dot-color: #fff;

    position: relative;
    top: -0.625em;
    display: grid;
    padding: 0.25em;
    border: 0.5em solid var(--marker-color);
    border-radius: 50%;
    background-color: var(--marker-dot-color);
    block-size: 0.5em;
    inline-size: 0.5em;

    &::after {
      position: absolute;
      bottom: -1.875em;
      left: -0.375em;
      width: 0;
      height: 0;
      border: 0.625em solid transparent;
      border-top: 1.0625em solid var(--marker-color);
      content: '';
    }
  }
}
```

<img width="811" alt="Screenshot 2024-02-23 at 21 07 47" src="https://github.com/visgl/react-google-maps/assets/1931880/53d5b90c-4de2-4481-9d54-76b3435f21af">

**Comment by usefulthink** [comment]
First, I would suggest to not use the same marker for both the Infowindow and actual marker, that would only be useful if you're planning to animate between them or something. Just make two in the same location instead. 

To handle the overlapping, you can use the [`zIndex`](https://developers.google.com/maps/documentation/javascript/reference/advanced-markers#AdvancedMarkerElement.zIndex) and [`collisionBehavior`](https://developers.google.com/maps/documentation/javascript/reference/advanced-markers#AdvancedMarkerElementOptions.collisionBehavior) props of the AdvancedMarker component. 

(I just noticed that the AdvancedMarker documentation page really needs to be improved...)

**Reply by rol4nd909** [reply]
Ah ok, thanks gonna give it a try 😊

**Reply by usefulthink** [reply]
this is what I meant with animating between an "light infowindow" and marker: https://storage.googleapis.com/gmp-maps-demos/advanced-markers/index.html#weather-marker

**Reply by rol4nd909** [reply]
Yeah I saw that one, it's way to fancy for what I need 😊

**Reply by rol4nd909** [reply]
I'm almost there, one thing left I have buttons inside and those are not clickable.
If I add `draggable={true}` to the `<AdvancedMarker>` than it works but I also able to drag it arronund.

```tsx
  return (
    <>
      <AdvancedMarker
        onClick={() => onToggle(!isOpen)}
        position={{
          lat: Number(dealer.location_lat),
          lng: Number(dealer.location_long),
        }}
        title={dealer.name}
        collisionBehavior={google.maps.CollisionBehavior.OPTIONAL_AND_HIDES_LOWER_PRIORITY}
      >
        <div className={classes.mapMarker} />
      </AdvancedMarker>

      {isOpen && (
        <AdvancedMarker
          position={{
            lat: Number(dealer.location_lat),
            lng: Number(dealer.location_long),
          }}
          className={classes.mapInfoWindow}
          zIndex={google.maps.Marker.MAX_ZINDEX + 1}
        >
          <button onClick={() => onToggle(!isOpen)}>X</button>
          <strong>{dealer.name}</strong>
          <address>
            {dealer.street_name} {dealer.house_number}
            <br />
            {dealer.zipcode}, {dealer.city}
          </address>

          <button
            className={classes.mapsSelectDealerButton}
            type="button"
            onClick={() => setValue(name, dealer.id.toString())}
          >
            {String(dealer.id) === value ? translations.selected : translations.select}
          </button>
        </AdvancedMarker>
      )}
    </>
  )
```

**Reply by usefulthink** [reply]
just guessing, but can you try to add `pointer-events:all` to the mapInfoWindow class in css?

**Reply by rol4nd909** [reply]
`pointer-events: all !important` did the trick!

Thanks a lot for your help, now searching for a way to center and zoom the selected marker :)

**Comment by lucksp** [comment]
what weird is there is all the padding & the close "X" is not visible... is that really editable without injecting a bunch of custom CSS?  It doesn't feel very react like...

**Comment by chama-x** [comment]
Here's a quick summary of the working solution:

**For custom InfoWindow styling with `<AdvancedMarker>`:**

1. **Basic HTML content** - Use `<AdvancedMarker>` which accepts any HTML as content via the children prop

2. **Handle button/clickable elements** - Add this CSS fix:
```css
.mapInfoWindow {
  pointer-events: all !important;
}
```
Without this, clicks on elements inside get intercepted by the map.

3. **Prevent unwanted dragging** - If you don't want the marker draggable, don't set `draggable={true}`. The `pointer-events: all` fix handles clicks without needing draggable.

4. **Z-index & overlap issues** - Use `zIndex` and `collisionBehavior` props on `<AdvancedMarker>` to control how markers layer when overlapping

5. **Styling** - You're free to use CSS classes for custom styling - just make sure the parent container has `display: grid` or similar if you want proper layout

**Why this works:**
Google Maps overlays capture pointer events by default. `pointer-events: all` ensures your custom content can interact normally with click handlers, buttons, and forms inside the info window.
