### DISCUSSION TITLE
About advancedMarker Animation

### DISCUSSION THREAD

**Discussion by abb438** [visgl/react-google-maps#368] [Q&A]
I want to reproduce the Drop and Bounce animation of the old Marker class using advancedMarker + Pin Component.
In the code below, .bounce is added to div.GMAMP-maps-pin-view and the bounce animation is working correctly, but when I click on the Marker, the .bounce is removed and the animation stops.
I could not find a method to animate AdvancedMarkerComponent in the docs, example, so I used https://developers.google.com/maps/documentation/javascript/examples/ advanced-markers-animation
as a reference.
Is this the wrong method to begin with?
```tsx
 const [instance, setInstance] = useState<google.maps.marker.AdvancedMarkerElement | null>(null);
 const setMarkerRef = (markerRef: google.maps.marker.AdvancedMarkerElement | null) => {
    if (instance === null) {
      if (markerRef) {
        setInstance(markerRef);
      }
    }
  };

useEffect(() => {
    if (instance) {
     const markerContent = instance.content as HTMLElement;
     markerContent.classList.add('bounce');
    }
  }, [instance]);
 
 return(
  <AdvancedMarker
      position={position}
      ref={setMarkerRef}
    >
      <Pin>
          <Box
            className='el_mapsMarker'
            width="max-content"
            color="#fff"
            fontFamily="sans-serif"
            fontSize="1.2rem"
            fontWeight="bold"
          >
            {labelText}
          </Box>
        </Pin>
    </AdvancedMarker>
 )
```

css 
```css
@keyframes bounce {
  0% {
    transform: translateY(0);
  }
  65% {
    transform: translateY(-15px);
  }
  100% {
    transform: translateY(0px);
  }
}

.bounce {
  animation: bounce .75s ease-out infinite;
}
```
